//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "ingredient")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub quantity_in_stock: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::ingredients_to_meals::Entity")]
    IngredientsToMeals,
}

impl Related<super::ingredients_to_meals::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IngredientsToMeals.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
