//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::ingredient::Entity as Ingredient;
pub use super::ingredients_to_meals::Entity as IngredientsToMeals;
pub use super::meal::Entity as Meal;
